sudo: required

services:
  - docker

branches:
  only:
    - master

install:
  - docker build -t hnakamur/libvmodcookierpm .

script:
  - docker run hnakamur/libvmodcookierpm "$COPR_LOGIN" "$COPR_USERNAME" "$COPR_TOKEN"
